import Foundation
import XCTest

@testable import RhinestoneDepositModal

/**
 The published contract, and the machinery to replay it.

 `bridge-transcript.json` is generated by the page from what actually crossed
 the channel, and vendored here. It records SHAPES rather than values and a SET
 rather than a sequence: what it pins is the vocabulary, the fields and their
 types, which is exactly what four hand-written copies of the protocol drift on.

 Refresh it from a served origin, never from the `deposit-modal` checkout —
 `modalVersion` is stamped at page build, and a copy without one cannot be
 dated:

     curl -fsS https://dev.deposit.rhinestone.dev/bridge-transcript.json \
       -o Tests/RhinestoneDepositModalTests/Resources/bridge-transcript.json
 */
indirect enum Shape: Decodable, Equatable {
    /// A type name (`string`, `number`, `boolean`, `null`, `undefined`, `[]`)
    /// or a literal, which is vocabulary.
    case leaf(String)
    case object([String: Shape])
    /// One element is an array shape; more is a union of the alternatives the
    /// field was seen carrying.
    case array([Shape])

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let leaf = try? container.decode(String.self) {
            self = .leaf(leaf)
        } else if let array = try? container.decode([Shape].self) {
            self = .array(array)
        } else {
            self = .object(try container.decode([String: Shape].self))
        }
    }

    static let leafTypes: Set<String> = [
        "string", "number", "boolean", "null", "undefined", "[]",
    ]

    /// The names the artifact uses for a leaf. Anything else at a leaf is a
    /// literal, and a literal constrains an answer's TYPE here — the vocabulary
    /// string itself is pinned against `Protocol.swift` separately.
    static func leafType(_ shape: String) -> String {
        leafTypes.contains(shape) ? shape : "string"
    }

    var isTuple: Bool {
        guard case .object(let fields) = self, !fields.isEmpty else { return false }
        return fields.keys.allSatisfy { Int($0) != nil }
            && Set(fields.keys.compactMap(Int.init)) == Set(0..<fields.count)
    }
}

struct TranscriptFrame: Decodable {
    let dir: String
    let kind: String
    let method: String?
    /// The CAIP-27 inner method. Part of a `wallet.request` frame's identity,
    /// because the params shape is the wallet method's, not the envelope's.
    let walletMethod: String?
    let type: String?
    let answers: String?
    let ok: Bool?
    let errorCode: Int?
    let errorDomain: String?
    let passthrough: Bool?
    let shape: Shape?
}

struct TranscriptVocabulary: Decodable {
    struct Channels: Decodable {
        let pageToHost: String
        let hostToPage: String
    }

    struct SignRecoveryConstants: Decodable {
        let domain: [String: String]
        let primaryType: String
        let encodeType: String
        let domainEncodeType: String
    }

    let `protocol`: Int
    let channels: Channels
    let maxFrameLength: Int
    let pageMethods: [String]
    let hostMethods: [String]
    let pageEvents: [String]
    let hostEvents: [String]
    let capabilities: [String]
    let walletMethods: [String]
    let errorDomain: String
    let errorCodes: [String: Int]
    let dismissalReasons: [String]
    let dismissSources: [String]
    let signRecovery: SignRecoveryConstants?
}

struct Transcript: Decodable {
    let transcriptFormat: Int
    let modalVersion: String?
    let vocabulary: TranscriptVocabulary
    let frames: [TranscriptFrame]

    static let supportedFormat = 1

    static func load() throws -> Transcript {
        guard
            let url = Bundle.module.url(
                forResource: "bridge-transcript",
                withExtension: "json"
            )
        else {
            throw XCTSkip("bridge-transcript.json is not in the test bundle.")
        }
        return try JSONDecoder().decode(Transcript.self, from: Data(contentsOf: url))
    }
}

/**
 Leaves whose placeholder has to be a real value.

 A host rejects `"x"` where it needs an `https:` URL or an address, so the
 replay would be testing the rejection rather than the contract. Keyed by field
 name and by leaf type, because two contracts share `chainId`: a bare id for the
 transaction methods, a CAIP-2 reference for CAIP-27. Keyed by name alone they
 collapse, and the replay drives a number where the page sends `eip155:8453`.
 */
enum ConstrainedLeaf {
    static let strings: [String: String] = [
        "url": "https://pay.example.com/order",
        "to": "0x2222222222222222222222222222222222222222",
        "from": "0x1111111111111111111111111111111111111111",
        "signer": "0x1111111111111111111111111111111111111111",
        "destination": "0x2222222222222222222222222222222222222222",
        "token": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
        "amount": "1000000",
        "depositId": "4242",
        "chainId": "eip155:8453",
    ]

    static let numbers: [String: Double] = ["chainId": 8453]
}

/**
 Build a concrete value the recorded shape describes — the inverse of the page's
 `shapeOf`.

 A literal in the shape is vocabulary and is reproduced exactly, which is the
 point of recording it as one; a leaf type name becomes a placeholder, since no
 value at that position is contractual. A union takes the first alternative that
 is not `undefined`, so an optional field is exercised present rather than
 skipped.
 */
func materialize(_ shape: Shape, key: String = "") -> JSONValue? {
    switch shape {
    case .leaf(let leaf):
        switch leaf {
        case "string": return .string(ConstrainedLeaf.strings[key] ?? "x")
        case "number": return .number(ConstrainedLeaf.numbers[key] ?? 1)
        case "boolean": return .bool(true)
        case "null": return .null
        case "undefined": return nil
        case "[]": return .array([])
        // A literal: a method name, a dismissal reason, a discriminant.
        default: return .string(leaf)
        }

    case .array(let options):
        if options.isEmpty { return .array([]) }
        if options.count == 1 {
            guard let element = materialize(options[0], key: key) else { return .array([]) }
            return .array([element])
        }
        let preferred = options.first { $0 != .leaf("undefined") } ?? options[0]
        return materialize(preferred, key: key)

    case .object(let fields):
        // Before the record branch: a tuple is an ARRAY on the wire, and
        // handing a provider `{"0": …}` where it expects `[…]` is a malformed
        // request.
        if shape.isTuple {
            let ordered = fields.keys.compactMap(Int.init).sorted()
            return .array(
                ordered.compactMap { index in
                    fields["\(index)"].flatMap { materialize($0, key: key) }
                }
            )
        }
        var value: [String: JSONValue] = [:]
        for (field, entry) in fields {
            if let built = materialize(entry, key: field) { value[field] = built }
        }
        return .object(value)
    }
}

/**
 Reduce a value to the same vocabulary the artifact uses, so an answer can be
 compared against a recorded one.

 Only the structure is compared, so literals collapse to their type here — the
 recorded side is what pins a vocabulary string, and it is checked separately.
 */
func structureOf(_ value: JSONValue?) -> Shape {
    guard let value else { return .leaf("undefined") }
    switch value {
    case .null: return .leaf("null")
    case .bool: return .leaf("boolean")
    case .number: return .leaf("number")
    case .string: return .leaf("string")
    case .array(let elements):
        return elements.isEmpty ? .leaf("[]") : .array([structureOf(elements[0])])
    case .object(let fields):
        var record: [String: Shape] = [:]
        for (key, entry) in fields { record[key] = structureOf(entry) }
        return .object(record)
    }
}

/**
 How an answer's structure fails the recorded shape, as a list of reasons.

 Presence is not conformance. A field the page retyped from `number` to `string`
 is drift this host would keep answering the old way, and a field that became an
 object is drift the page would read as `undefined` — so leaves are compared by
 type and containers by kind, not by key alone.

 Only the recorded side constrains: an answer carrying a field that was never
 recorded is an addition, which the contract permits. A union carrying
 `undefined` is the page's way of recording a field seen present in one scenario
 and absent in another, which is the one fact a native decoder cannot infer from
 a single example — an answer may omit it.
 */
func mismatches(_ actual: Shape, _ recorded: Shape, path: String = "") -> [String] {
    let at = path.isEmpty ? "the result" : path

    switch recorded {
    case .array(let options):
        if options.isEmpty { return [] }
        if options.count == 1 {
            if actual == .leaf("[]") { return [] }
            if case .array(let actualElements) = actual, actualElements.count == 1 {
                return mismatches(actualElements[0], options[0], path: "\(path)[]")
            }
            return ["\(at): expected an array, got \(actual)"]
        }
        if options.contains(.leaf("undefined")), actual == .leaf("undefined") { return [] }
        let alternatives = options.filter { $0 != .leaf("undefined") }
        func satisfies(_ candidate: Shape) -> Bool {
            alternatives.contains { mismatches(candidate, $0, path: path).isEmpty }
        }
        if satisfies(actual) { return [] }
        // An array whose elements carried differing shapes is written the same
        // way as a union, so an array of one of the alternatives satisfies it
        // too — `capabilities` is recorded exactly that way.
        if case .array(let actualElements) = actual, actualElements.count == 1,
            satisfies(actualElements[0])
        {
            return []
        }
        return ["\(at): expected one of \(options), got \(actual)"]

    case .object(let fields):
        // An empty record was recorded carrying nothing, so it constrains
        // nothing.
        if fields.isEmpty { return [] }
        guard case .object(let actualFields) = actual else {
            return ["\(at): expected an object, got \(actual)"]
        }
        return fields.flatMap { key, entry in
            mismatches(
                actualFields[key] ?? .leaf("undefined"),
                entry,
                path: path.isEmpty ? key : "\(path).\(key)"
            )
        }

    case .leaf(let leaf):
        let want = Shape.leafType(leaf)
        if case .leaf(let actualLeaf) = actual, Shape.leafType(actualLeaf) == want { return [] }
        return ["\(at): expected \(want), got \(actual)"]
    }
}
